name: "ALTO to TEI Workflow"
'on':
  - push
  - pull_request
jobs:
  ALTO2TEI:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install requests
          pip install pyyaml
      - name: "Create TEI files"
        run: |
         python alto2tei/run.py --config config.yml --version "3.0.13" --header --sourcedoc --body
      - name: "Commit generated files to data/"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./data/*.xml
          git commit -m "[Automatic] Create TEI files" || echo "Nothing to commit"
          git push || echo "Nothing to push"
