name: "Text Extraction Workflow"
on:
  - push
  - pull_request
jobs:
  MainZone:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: "Extract and collate text from files' MainZones"
        run: |
          python text-extraction.py ./data/*
      - name: "Commit generated text files to ./data/"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./data/*.txt
          git commit -m "Extract text from documents' MainZones" || echo "Nothing to commit"
          git push || echo "Nothing to push"

